### ISSUE TITLE
파일 명, 변수 명을 함부로 짓지 말것.

### ISSUE THREAD

**Issue by dotori1995-enu** [kongukjae/KDT-2-Project-A-1#3]
test-enui.js 같이 파일의 존재 이유를 알수 없는 파일 명으로 짓지 말것. 이름은 해당 존재에 대한 개념을 내포함은 물론 존재의 당위성 까지 설명 가능해야함

**Comment by HaekyungS** [comment]
네, 유의하도록 하겠습니다.
