### ISSUE TITLE
홈 화면 기능구현 2

### ISSUE THREAD

**Issue by RyuEuni** [kongukjae/KDT-2-Project-A-1#30]

**Comment by EXPNUNI-HUB** [comment]
코드를 확인할 수 있게 git에 올려주길 바람. 많이 확인 받은 코드가 덜 확인 받은 코드보다 정교해짐

**Comment by HaekyungS** [comment]
확인 가능하시도록 main에 merge 해서 push 하였습니다.
main merge 이 전에 master라는 브랜치에 merge 를 진행 중이기에 참고하여 주시길 바랍니다.
현재는 master와 main이 동일한 상태입니다.

**Comment by dotori1995-enu** [comment]
Git 사용시 마스터와 브랜치 등 하나의 프로젝트에 대해 여러 가지 버전을 만들 수 있음. 단, 각 버전에 대한 버전관리에 대해 실패하지 않는다면. 여러 브랜치를 만들 경우, 마스터 관리는 꼭 잘 하길 바람. 마스터 관리를 못하면 후에 기능이 꼬이게 됨.

**Comment by HaekyungS** [comment]
네. 유의하여 잘 관리하도록 하겠습니다.
