### ISSUE TITLE
파이썬을 nodejs 에서 실행하기

### ISSUE THREAD

**Issue by HaekyungS** [kongukjae/KDT-2-Project-A-1#9]

**Comment by EXPNUNI-HUB** [comment]
파이썬을 nodejs에서 실행하는 이유가 궁금함.

**Comment by HaekyungS** [comment]
증권사 실시간 데이터를 파이썬 함수를 사용하여 불러오는 테스트 과정에서 nodejs 에서 해당 함수를 실행하여 바로 사용이 가능한지에 대한 여부가 궁금하여 테스트를 해봤습니다.
